version: '2'

services:
    db:
        image: mysql
        expose:
            - "3306"
        volumes:
            - ./data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: nk8w7rfU7y8prHe9SWww3za3GbckVDUahdPDkWvSTR4nyTJvCHA4MEQYPymz2sfL
            MYSQL_DATABASE: sanrafaelDBbF6KXq
            MYSQL_USER: sanrafaelUserNameg4m6Wb
            MYSQL_PASSWORD: nfNw9VhbKEPQzLgd6JXvW8T6bNB2sYksAWcd8VVZU7wfTGgUR9h4kBVkT4LqTEV8
    php:
        build: ./docker/php-fpm
        expose:
            - "9001"
        volumes_from:
            - sync
        working_dir: /var/www/symfony
        volumes:
            - ./logs/symfony:/var/www/symfony/var/logs
        restart: always
        links:
            - db
            - sync
    nginx:
        build: ./docker/nginx
        ports:
            - "8088:80"
        links:
            - php
        volumes_from:
            - sync
        volumes:
            - ./logs/nginx/:/var/log/nginx
        restart: always
    elk:
        image: willdurand/elk
        ports:
            - "83:80"
        volumes:
            - ./docker/elk/logstash:/etc/logstash
            - ./docker/elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - sync
            - nginx
    # Synchronization
    sync:
        build: ./docker/sync
        command: "lsyncd -delay 1 -nodaemon -rsync /src /var/www/symfony"
        volumes:
            - /var/www/symfony
            - "./web/:/src"
        working_dir: /src
        stdin_open: true
        tty: true